name: brekete_connect
description: Brekete Family Connect App.

version: 1.1.5+33

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chewie: ^1.3.4
  cloud_firestore: ^3.4.0
  cupertino_icons: ^1.0.5
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.3
  flutter:
    sdk: flutter
  flutter_facebook_login: ^3.0.0
  flutter_inappwebview: ^5.4.3+7
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  google_sign_in: ^5.4.0
  image_picker: ^0.8.5+3
  #modal_progress_hud: ^0.1.3
  modal_progress_hud_alt: ^1.0.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.6
  url_launcher: ^6.1.5
  video_player: ^2.4.5
  webview_flutter: ^3.0.4
  cached_network_image: ^3.2.1
  badges: ^2.0.3
  timeago: ^3.2.2
  carousel_slider: ^4.1.1
  open_file: ^3.2.1
  flowder: ^0.2.0
  #percent_indicator: ^4.2.1
  percent_indicator: ^4.2.2
  font_awesome_flutter: ^10.1.0



  #Just added packages   --BEGIN--
  json_annotation: ^4.6.0
  day_night_switcher: ^0.2.0+1
  #provider: ^5.0.0
  #cupertino_icons: ^1.0.2
  #font_awesome_flutter: ^9.0.0
  google_fonts: ^3.0.1
  rxdart: ^0.27.5
  another_flushbar: ^1.10.29
  #cached_network_image: ^3.0.0
  connectivity: ^3.0.6
  #image_picker: ^0.7.5+2
  page_transition: ^2.0.9
  #timeago: ^3.0.2
  file_picker: ^4.6.1
  #percent_indicator: ^3.0.1
  #shared_preferences: ^2.0.5
  custom_navigation_bar: ^0.8.2
  # multi_image_picker2: ^5.0.0
  flutter_slidable: ^2.0.0
  #path_provider: ^2.0.2
  material_dialogs: ^1.1.3
  intl: ^0.17.0
  flutter_downloader: ^1.8.1
  photo_view: ^0.14.0
  emoji_picker_flutter: ^1.3.0
  #agora video call
  agora_rtc_engine: ^5.3.0
  #permission handler
  #permission_handler: ^6.0.1
  #video_player: ^2.1.14
  #SVG Package
  flutter_svg: ^1.1.1+1
  #status bar color
  flutter_statusbarcolor_ns: ^0.4.0
  #GIF Packages
  giphy_get: ^2.0.4
  #google sign in
  #google_sign_in: ^5.0.5

  #SQL for local Storage
  hive: ^2.2.3
  sqflite: ^2.0.3

  #Search Bar packages
  flappy_search_bar_ns: ^2.0.2

  #firebase packages
  #firebase_core: ^1.2.0
  firebase_analytics: ^9.2.1
  #firebase_auth: ^1.2.0
  #cloud_firestore: ^2.2.0
  #firebase_storage: ^8.1.0
  flutter_launcher_icons: ^0.9.3
  #Just added packages   --END--



dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appIcon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - images/
    - assets/images/
    - assets/logo/
    - assets/icons/
  #  - images/a_dot_ham.jpeg
 